# Generated by Django 4.2.25 on 2025-10-06 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentmngs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Studentmngs',
        ),
    ]
