# Generated by Django 4.2.25 on 2025-10-06 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentmngs', '0002_rename_student_studentmngs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('course', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Studentmngs',
        ),
    ]
